services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DB_HOST: 172.16.0.200
      DB_PORT: 3306
      DB_DATABASE: app_backend
      DB_USERNAME: app_backend
      DB_PASSWORD: password
    networks:
      backend:
        ipv4_address: 172.16.0.100
  
  database:
    image: mariadb:lts
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: app_backend
      MARIADB_USER: app_backend
      MARIADB_PASSWORD: password
    networks:
      backend:
        ipv4_address: 172.16.0.200

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"

